bmxwebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('clubs/', include('clubs.urls')),
    path('riders/', include('riders.urls')),
    path('events/', include('events.urls')),
    path('rankings/', include('rankings.urls')),
    path('dashboards/', include('dashboards.urls')),
]

clubs/urls.py
from django.contrib import admin
from django.urls import path
from clubs import views

app_name = 'clubs'

urlpatterns = [
    path('', views.clubs, name="clubs"),
    path('detail/<str:pk>', views.club_detail, name="club-detail")
]

riders/urls.py
from django.urls import path
from riders import views

app_name = 'riders'

urlpatterns = [
    path('', views.riders, name="riders"),
    # path('detail/<str:pk>', views.rider_detail, name="rider-detail"),
    path('plate_req/', views.plate_req, name="plate-req"),
    path('importcsv/', views.import_csv, name="importcsv"),
    path('validation_licence/', views.validation_licence, name="validation-licence"),
]

riders/models.py
from django.db import models
from clubs.models import Club


# Create your models here.

class Rider(models.Model):
    GENDER = (('Muž/Male', 'Muž/Male'), ('Žena/Female', 'Žena/Female'), ('Ostatní/Other', 'Ostatní/Other'))

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    date_of_birth = models.DateField(blank=True, null=True)

    uci_id = models.CharField(max_length=255, unique=True)

    gender = models.CharField(max_length=50, default='Muž/Male', choices=GENDER)

    nationality = models.CharField(max_length=3, default='CZE')

    email = models.EmailField(blank=True, null=True)

    club = models.ForeignKey(Club, null=True, on_delete=models.SET_NULL)

    plate = models.IntegerField()
    plate_2 = models.IntegerField(null=True, blank=True)

    transponder_20 = models.CharField(max_length=10, null=True, blank=True)
    is_valid_transponder_20 = models.BooleanField(default=True)
    transponder_24 = models.CharField(max_length=10, null=True, blank=True)
    is_valid_transponder_24 = models.BooleanField(default=True)
    transponder_mtb = models.CharField(max_length=10, null=True, blank=True)
    is_valid_transponder_mtb = models.BooleanField(default=True)
    transponder_other = models.CharField(max_length=10, null=True, blank=True)
    is_valid_transponder_other = models.BooleanField(default=True)

    emergency_contact = models.CharField(max_length=255, null=True, blank=True)
    emergency_phone = models.CharField(max_length=255, null=True, blank=True)

    is_challenge = models.BooleanField(default=True)
    is_elite = models.BooleanField(default=False)
    is_cruiser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_approwed = models.BooleanField(default=False)

    have_valid_licence = models.BooleanField(default=True)

    path_to_photo = models.CharField(max_length=255, null=True, blank=True)

    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        full_name = self.last_name + " " + self.first_name + " UCI ID: " + self.uci_id
        return full_name

    def lastNameUppercase(self):
        return self.last_name.upper()

riders/forms.py
from django.forms import ModelForm
from .models import Rider


class RiderForm(ModelForm):
    class Meta:
        model = Rider
        exclude = ('is_approwed','is_active',)

riders/views.py
from django.shortcuts import render, redirect
from .models import Rider
from clubs.models import Club
from .forms import RiderForm
from .func import import_csv, validation_licence


# Create your views here.

def riders(request):
    if request.method == 'POST':
        pass
    else:
        riders = Rider.objects.filter(is_active="True")
        context = {"riders": riders}
        return render(request, 'riders/riders.html', context)


def plate_req(request):
    if request.method == 'POST':
        form = RiderForm(request.POST)
        if form.is_valid():
            print("Žádost o číslo - data validní")
            form.save()
        else:
            print("Data žádosti o číslo nejsou validní")
        return redirect('riders:riders')

    else:
        all_plates = []
        for plate in range(10, 1000):
            all_plates.append(plate)
        used_plates = []
        riders = Rider.objects.filter(is_active="True")
        for rider in riders:
            used_plates.append(rider.plate)
        for used_plate in used_plates:
            all_plates.remove(used_plate)  # ze všech čísel vymažu ty již obsazená aktivními jezdci
        print(all_plates)
        form = RiderForm()
        clubs = Club.objects.order_by('name')

        context = {'form': form, 'clubs': clubs, 'free_plates': all_plates}

        return render(request, 'riders/plate_req.html', context)

riders/templates/riders/plate_req.html
{% extends 'articles/base.html' %}

{% block content %}
<br>
<br>
<div class="container"><h1 class="text-center">Žádost o přidělení startovního čísla</h1></div>
<br>

<div class="container">
    <form action="" method="post" class ="needs-validation">
        {% csrf_token %}

        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="id_uci_id">UCI ID:</label>
                    <input type="text" name="uci_id" maxlength="255" required id="id_uci_id" class="form-control is-valid">
                    <div class="valid-feedback">UCI ID ověřeno</div>
                    <div class="invalid-feedback">UCI ID neexistuje</div>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="id_plate">Vyber si startovní číslo:</label>
                    <select name="plate" required id="id_plate" class="form-control">
                        <option value="" selected>---------</option>
                        {% for plate in free_plates %}
                        <option value="{{ plate }}">{{ plate }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="id_first_name">Jméno:</label>
                    <input type="text" name="first_name" maxlength="255" required id="id_first_name"
                           class="form-control" >
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="id_last_name">Příjmení:</label>
                    <input type="text" name="last_name" maxlength="255" required id="id_last_name" class="form-control">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="id_date_of_birth">Datum narození:</label>
                    <input type="text" name="date_of_birth" id="id_date_of_birth" class="form-control">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="id_gender">Pohlaví:</label>
                    <select name="gender" id="id_gender" class="form-control">
                        <option value="Muž/Male">Muž/Male</option>
                        <option value="Žena/Female">Žena/Female</option>
                        <option value="Ostatní/Other">Ostatní/Other</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="id_email">Zadej svůj e-mail:</label>
                    <input type="email" name="email" maxlength="254" id="id_email" class="form-control">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="id_club">Zadej svůj klub:</label>
                    <select name="club" required id="id_club" class="form-control">
                        <option value="" selected>---------</option>
                        {% for club in clubs %}
                        <option value="{{ club.id }}">{{ club.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="id_emergency_contact">Kontaktní osoba pro případ nouze:</label>
                    <input type="text" name="emergency_contact" maxlength="255" id="id_emergency_contact"
                           class="form-control">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="id_emergency_phone">Telefon na nouzový kontakt:</label>
                    <input type="text" name="emergency_phone" maxlength="255" id="id_emergency_phone"
                           class="form-control">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <div class="form-check">
                        <input type="checkbox" name="is_challenge" id="id_is_challenge" checked
                               class="form-check-input">
                        <label for="id_is_challenge" class="form-check-label">Jezdíš na 20" kole?</label>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <div class="form-check">
                        <input type="checkbox" name="is_cruiser" id="id_is_cruiser" class="form-check-input">
                        <label for="id_is_cruiser" class="form-check-label">Jezdíš na 24" kole (cruiser)?</label>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <div class="form-check">
                        <input type="checkbox" name="is_elite" id="id_is_elite" class="form-check-input">
                        <label for="id_is_elite" class="form-check-label">Jsi jezdec kategorie Junior/Elite?</label>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col"></div>
            <div class="col">
                <button type="submit" class="btn btn-success" >Odešli žádost o startovní číslo</button>
            </div>
            <div class="col"></div>
        </div>
    </form>

</div>

{% endblock %}

riders/templates/riders/rider_create.html
{% extends 'articles/base.html' %}

{% block content %}
<br>
<div class = "container"><h1 class = "text-center">Seznam jezdců</h1></div>

<br>
<div class="container">



</div>

{% endblock %}

riders/templates/riders/riders.html
{% extends 'articles/base.html' %}

{% block content %}
<br>
<div class = "container"><h1 class = "text-center">Seznam jezdců</h1></div>

<br>
<div class = "container">
<a href = "{% url 'riders:plate-req'%}">Zde</a> můžeš požádat o startovní číslo
</div>

<br>
<div class="container">
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">St.č.</th>
            <th scope="col">Příjmení</th>
            <th scope="col">Jméno</th>
            <th scope="col">UCI ID</th>
            <th scope="col">Klub</th>
            <th scope="col">Poznámka</th>
            <th scope="col">Detail jezdce</th>
        </tr>
        </thead>
        <tbody>
        {% for rider in riders %}
        <tr>
            <th scope="row" class = "">{{ rider.plate }}</th>


            <td>{{ rider.last_name }}</td>



            <td>{{ rider.first_name }}</td>
            <td>{{ rider.uci_id }}</td>
            <td>{{ rider.club }}</td>
            {% if rider.have_valid_licence %}
            <td></td>
            {% else %}
            <td class = "badge badge-danger text-wrap align-middle ">NEPLATNÁ LICENCE PRO TENTO ROK</td>
            {% endif%}
            <td>detail</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>

{% endblock %}