articles/urls.py
from django.urls import path
from articles import views

app_name = 'articles'

urlpatterns = [
    path('', views.home, name="home"),
    path('articles/', views.articles, name="articles")
]

bmxwebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('clubs/', include('clubs.urls')),
    path('riders/', include('riders.urls')),
    path('events/', include('events.urls')),
    path('rankings/', include('rankings.urls')),
    path('dashboards/', include('dashboards.urls')),
]

clubs/urls.py
from django.contrib import admin
from django.urls import path
from clubs import views

app_name = 'clubs'

urlpatterns = [
    path('', views.clubs, name="clubs"),
    path('detail/<str:pk>', views.club_detail, name="club-detail")
]

dashboards/urls.py
from django.urls import path
from dashboards import views

app_name = 'dashboards'

urlpatterns = [
    path('', views.dashboards, name="dashboards"),
    #path('detail/<str:pk>', views.club_detail, name="club-detail")
]

events/urls.py
from django.urls import path
from events import views

app_name = 'events'

urlpatterns = [
    path('', views.events, name="events"),
]

riders/urls.py
from django.urls import path
from riders import views

app_name = 'riders'

urlpatterns = [
    path('', views.riders, name="riders"),
    # path('detail/<str:pk>', views.rider_detail, name="rider-detail"),
    path('plate_req/', views.plate_req, name="plate-req"),
    path('importcsv/', views.import_csv, name="importcsv"),
    path('validation_licence/', views.validation_licence, name="validation-licence"),
]

articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    #author = models.CharField()

    on_headline = models.BooleanField(default=False)
    headline_positions = models.IntegerField()

    path_to_image = models.CharField(max_length=255, null = True, blank = True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.title

articles/views.py
from django.shortcuts import render
from riders.models import Rider
from clubs.models import Club
from events.models import Event
#from articles.models import Article
from datetime import date


# Create your views here.

def home(request):
    if request == 'POST':
        pass
    else:
        now = date.today()
        now = now.year

        riders = Rider.objects.filter(is_active=True).count()
        clubs = Club.objects.filter(is_active=True).count()
        events = Event.objects.filter(date__year=str(now)).count()
       # articles = Article.objects.all().count()

        context = {'riders': riders, 'clubs': clubs, 'events': events,}
        return render(request, 'articles/home.html', context)

def articles(request):
    if request == 'POST':
        pass
    else:
        context = {}
        return render(request, 'articles/articles.html', context)

articles/templates/articles/articles.html
{% extends 'articles/base.html' %}

{% block content %}

<h1>Seznam článků</h1>

{% endblock %}

articles/templates/articles/base.html
<!doctype html>
<html lang="cs">

{% load static %}

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Czech BMX website</title>
  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">czech bmx website</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="{% url 'articles:home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'articles:articles' %}">Články</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'events:events' %}">Kalendář závodů</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Ranking</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'clubs:clubs' %}">Kluby</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'riders:riders' %}">Jezdci</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboards:dashboards' %}">Administrace</a>
      </li>

<!--    <form class="form-inline my-2 my-lg-0">-->
<!--      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--    </form>-->
  </div>
</nav>

    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

articles/templates/articles/home.html
{% extends 'articles/base.html' %}

{% block content %}

<h1>HOMEPAGE</h1>

{% endblock %}