bmxwebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('clubs/', include('clubs.urls')),
    path('riders/', include('riders.urls')),
    path('events/', include('events.urls')),
    path('rankings/', include('rankings.urls')),
    path('dashboards/', include('dashboards.urls')),
]

clubs/urls.py
from django.contrib import admin
from django.urls import path
from clubs import views

app_name = 'clubs'

urlpatterns = [
    path('', views.clubs, name="clubs"),
    path('detail/<str:pk>', views.club_detail, name="club-detail")
]

clubs/models.py
from django.db import models


# Create your models here.

class Club(models.Model):
    REGION = (
        ('Praha', 'Praha'), ('Středočeský', 'Středočeský'), ('Západočeský', 'Západočeský'), ('Jihočeský', 'Jihočeský'),
        ('Ústecký', 'Ústecký'), ('Plzeňský', 'Plzeňský'), ('Karlovarský', 'Karlovarský'),
        ('Liberecký', 'Liberecký'), ('Parbubický', 'Parbubický'), ('Královéhradecký', 'Královéhradecký'),
        ('Vysočina', 'Vysočina'), ('Jihomoravský', 'Jihomoravský'), ('Moravskoslezský', 'Moravskoslezský'),
        ('Olomoucký', 'Olomoucký'), ('Zlínský', 'Zlínský'),)
    name = models.CharField(max_length=200, null=True, unique=True)
    company_number = models.CharField(max_length=50, null=True, blank=True)

    street = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=255, null=True)
    post_no = models.CharField(max_length=50, null=True)
    region = models.CharField(max_length=255, null=True, choices=REGION)

    web = models.URLField(null=True, blank=True)
    contact_person = models.CharField(max_length=255, null=True, blank=True)
    contact_phone = models.CharField(max_length=255, null=True, blank=True)
    contact_email = models.EmailField(null=True, blank=True)

    bank_account = models.CharField(max_length=255, null=True, blank=True)
    bank_code = models.CharField(max_length=100, null=True, blank=True)
    swift = models.CharField(max_length=255, null=True, blank=True)
    iban = models.CharField(max_length=255, null=True, blank=True)

    paypal_id = models.CharField(max_length=255, null=True, blank=True)

    date_created = models.DateTimeField(auto_now_add=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

clubs/views.py
from django.shortcuts import render, redirect
from .models import *


# Create your views here.

def clubs(request):
    if request == 'POST':
        pass
    else:
        clubs = Club.objects.order_by('name')
        context = {"clubs":clubs}
        return render(request, 'clubs/clubs.html', context)


def club_detail(request, pk):
    if request == 'POST':
        pass
    else:
        club = Club.objects.get(id=pk)
        context = {"club":club}
        return render(request, 'clubs/club_detail.html', context)

clubs/templates/clubs/club_detail.html
{% extends 'articles/base.html' %}

{% block content %}

<h1 class="text-center ">Detail klubu</h1>

<br>

<div class="container">

    {{ club.name }}<br>
    {{ club.company_number }}<br>
    {{ club.street }}<br>
    {{ club.city }}<br>
    {{ club.post_no }}<br>
    {{ club.region }}<br>
    {{ club.web }}<br>
    {{ club.contact_person }}<br>
    {{ club.contact_phone }}<br>
    {{ club.contact_email }}<br>
<br>


</div>


{% endblock %}

clubs/templates/clubs/clubs.html
{% extends 'articles/base.html' %}

{% block content %}
<br>
<div class = "container"><h1 class = "text-center">Seznam klubů</h1></div>

<br>
<div class="container">
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Název klubu</th>
            <th scope="col">Město</th>
            <th scope="col">Kraj</th>
            <th scope="col">Detail</th>
        </tr>
        </thead>
        <tbody>
        {% for club in clubs %}
        <tr>
            <th scope="row">{{ club.name }}</th>
            <td>{{ club.city }}</td>
            <td>{{ club.region }}</td>
            <td><a href={% url 'clubs:club-detail' club.id %}> Detail</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    </table>
</div>

{% endblock %}